
micronaut:
  application:
    name: mnaut-pojo-mongo
netty:
  default:
    allocator:
      max-order: 3

mongodb.uri: mongodb://${MONGO_HOST:localhost}:${MONGO_PORT:27017}/micronaut-stuff2

jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    failOnUnknownProperties: false